import Head from 'next/head';

import Post from '../components/Post';
import Bio from '../components/Bio';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png'
          name='Farzam Mo'
          tagline='Learing NextJs & Figma'
          role='Junior Software Engineer'
        />

        <ul className={styles.posts}>
          <li>
            <Post
              content=" Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book."
              date='24/03/2022'
            />
          </li>
          <li>
            <Post
              content=" Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book."
              date='24/03/2022'
            />
          </li>
          <li>
            <Post
              content=" Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book."
              date='24/03/2022'
            />
          </li>
        </ul>
      </main>
    </div>
  );
}
